[tool.poe.tasks]
# Development tasks
install = { cmd = "uv sync --all-extras", help = "Install and sync project dependencies." }
sync = { cmd = "uv sync --all-extras", help = "Sync project dependencies. (Alias for install.)" }
format = { cmd = "uv run ruff format .", help = "Format code with ruff" }
lint = { cmd = "uv run ruff check .", help = "Lint code with ruff" }
lint-fix = { cmd = "uv run ruff check --fix .", help = "Lint and fix code with ruff" }
typecheck = { cmd = "uv run mypy builder_mcp", help = "Type check code with mypy" }
test = { cmd = "uv run pytest tests/ -v", help = "Run tests with verbose output" }
test-fast = { cmd = "uv run pytest --exitfirst tests", help = "Run tests, stop on first failure" }

# MCP server tasks
server = { cmd = "uv run builder-mcp", help = "Start the MCP server" }
inspect = { cmd = "uv run fastmcp inspect builder_mcp/server.py:app", help = "Inspect MCP tools" }

# Documentation tasks
docs-generate = { cmd = "uv run pdoc builder_mcp --output-dir docs/generated", help = "Generate API documentation" }

# Combined tasks
check = { sequence = ["lint", "typecheck", "test"], help = "Run all checks" }
