[project]
name = "airbyte-connector-builder-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.1.1",
    "pydantic-ai-slim[openai,duckduckgo,mcp]>=0.0.14,<1.0",
    "pydantic>=2.11.9,<3.0",
    "pyyaml>=6.0.1",
    "pandas>=2.0.0",
    "arize-phoenix-client>=1.19.1",
    "arize-phoenix-otel>=0.13.1",
    "arize-phoenix-evals>=2.1.0",
    "emoji>=2.15.0,<3.0",
    "airbyte-cdk>=7.3.8,<8.0",
    "openinference-instrumentation-pydantic-ai>=0.1.9",
]

[dependency-groups]
dev = [
    "poethepoet>=0.37.0",
    "pytest>=8.4.2",
    "pytest-asyncio>=0.23.0",
]
