name: GitHub Models CI Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - ready_for_review
      - reopened
      - synchronize
  workflow_dispatch:

permissions:
  contents: read
  models: read

jobs:
  test-github-models-agent:
    name: Test Connector Build
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
        - api_name: "JSONPlaceholder"
        - api_name: "PokemonTGG"
    steps:
      # Common steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up uv
        uses: astral-sh/setup-uv@v6.6.1
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install Poe Task Manager
        run: uv tool install poethepoet
      - name: Install dependencies
        run: uv sync --all-extras

      # Sync agents sub-project
      - name: Install agents dependencies
        run: uv sync --project connector_builder_agents --all-extras

      # Some MCP Servers need npx/node, so set that up:
      - name: Set up Node.js and npx
        uses: actions/setup-node@v5.0.0
        with:
          node-version: '20'

      # Job-specific step(s):
      - name: Run agent-based connector build
        timeout-minutes: 15
        continue-on-error: true  # TODO: Fails currently, needs more work
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_AGENTS_LOG: debug
          OPENAI_LOG: debug
          FASTMCP_DEBUG: 1
        run: |
          poe build-connector --api-name="${{ matrix.api_name }}"
