name: Dependency Analysis

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "uv.lock"
      - "pyproject.toml"
  pull_request:
    paths:
      - "src/**"
      - "uv.lock"
      - "pyproject.toml"

jobs:
  dependency-analysis:
    name: Dependency Analysis with Deptry
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Set up uv
        uses: astral-sh/setup-uv@v6.4.3
      - name: Install dependencies
        run: uv install --all-extras

      # Job-specific step(s):
      - name: Run Deptry
        run: |
          uv run deptry .
