name: Run Evals

on:
  workflow_dispatch:

jobs:
  run-evals:
    name: Run AI Builder Evals
    runs-on: ubuntu-24.04
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      PHOENIX_API_KEY: ${{ secrets.PHOENIX_API_KEY }}
      PHOENIX_COLLECTOR_ENDPOINT: "https://app.phoenix.arize.com/s/airbyte-ci"

    steps:
      # Some MCP Servers need npx/node, so set that up:
      - name: Set up Node.js and npx
        uses: actions/setup-node@v5.0.0
        with:
          node-version: '20'

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run Poe Slash Command Processor
        uses: aaronsteers/poe-command-processor@v1
        with:
          command: evals run
          github-token: ${{ secrets.GITHUB_TOKEN }}
